#ifndef BUTTON_DEFS_H
#define BUTTON_DEFS_H

typedef struct
{
    SDL_Rect rect;
    SDL_Color color;
    bool opacity: 1;
} rectangle_s;

typedef struct
{
    SDL_Rect rect;
    SDL_Color color;
    unsigned char radius;
    bool opacity: 1;
} rounded_rectangle_s;

typedef struct
{
   int x;
   int y;
   int Width;
   int Height;
   int button_idx;
   int txt_idx;
   int txt_group;
   int txt_offset;
   int back_ground_img_idx;
   int button_pressed_back_ground_img_idx;
   int icon_img_idx;
} button_grp_s;

typedef struct
{
   int x;
   int y;
   int Width;
   int Height;
   int button_idx;
} button_grp_0_s;

//Taustan pohjan rectanglet
extern rectangle_s Rect1;
extern rectangle_s Rect2;
extern rectangle_s Rect3;
extern rectangle_s Rect4;
extern rectangle_s Rect4_small;

extern rounded_rectangle_s temp_saato_rounded_rect;
#define TEMP_SAATO_BOX_Y  (137-5) //temp_saato_rounded_rect y-pos
#define AIKA_SAATO_BOX_Y  (368-5) //kuten temp_saato_rounded_rect mutta y-pos eri
#define VESI_SAATO_BOX_Y  (599-5) //kuten temp_saato_rounded_rect mutta y-pos eri
#define MIXER_SAATO_BOX_Y (834-5) //kuten temp_saato_rounded_rect mutta y-pos eri

extern rounded_rectangle_s aloita_rounded_rect;

#define PLUS_MIINUS_W 46

/*Ajonaikaiset lukemat Font=Simplon Norm Bold 80px/96px, color=FFFFFF */
#define TEMP_LUKEMA_T 146
#define TEMP_LUKEMA_L 453
#define TEMP_LUKEMA_W 194
#define TEMP_LUKEMA_H 92

#define TEMP_MIINUS_T 146
#define TEMP_MIINUS_L 398
#define TEMP_MIINUS_W PLUS_MIINUS_W
#define TEMP_MIINUS_H 92

#define TEMP_PLUS_T 146
#define TEMP_PLUS_L 673
#define TEMP_PLUS_W PLUS_MIINUS_W
#define TEMP_PLUS_H 92
/*-------------------------------------*/
#define AIKA_LUKEMA_T 377
#define AIKA_LUKEMA_L 450
#define AIKA_LUKEMA_W 200
#define AIKA_LUKEMA_H 92

#define AIKA_MIINUS_T 377
#define AIKA_MIINUS_L 398
#define AIKA_MIINUS_W PLUS_MIINUS_W
#define AIKA_MIINUS_H 92

#define AIKA_PLUS_T 377
#define AIKA_PLUS_L 673
#define AIKA_PLUS_W PLUS_MIINUS_W
#define AIKA_PLUS_H 92
/*-------------------------------------*/
#define VESI_LUKEMA_T 608
#define VESI_LUKEMA_L 464
#define VESI_LUKEMA_W 172
#define VESI_LUKEMA_H 92

#define VESI_MIINUS_T 608
#define VESI_MIINUS_L 398
#define VESI_MIINUS_W PLUS_MIINUS_W
#define VESI_MIINUS_H 92

#define VESI_PLUS_T 608
#define VESI_PLUS_L 673
#define VESI_PLUS_W PLUS_MIINUS_W
#define VESI_PLUS_H 92
/*-------------------------------------*/
#define MIX_LUKEMA_T 843
#define MIX_LUKEMA_L 484
#define MIX_LUKEMA_W 132
#define MIX_LUKEMA_H 92

#define MIX_MIINUS_T 843
#define MIX_MIINUS_L 398
#define MIX_MIINUS_W PLUS_MIINUS_W
#define MIX_MIINUS_H 92

#define MIX_PLUS_T 843
#define MIX_PLUS_L 673
#define MIX_PLUS_W PLUS_MIINUS_W
#define MIX_PLUS_H 92

/*----ALOITA PAINIKE-------*/
#define ALOITA_T 1038
#define ALOITA_L ((800-715)/2)
#define ALOITA_W 715
#define ALOITA_H 97

#define LOPETA_T 1038
#define LOPETA_L ((800-715)/2)
#define LOPETA_W 715
#define LOPETA_H 97

#define VALMIS_Y_OFFSET 100

/*----KOTINÄKYMÄ etc.-------*/
#define MENU_B_X0  20
#define MENU_B_X1 280
#define MENU_B_X2 540

#define MENU_B_Y0  90
#define MENU_B_Y1 350
#define MENU_B_Y2 610

#define MENU_BUTTON1_L MENU_B_X0
#define MENU_BUTTON1_T MENU_B_Y0

#define MENU_BUTTON2_L MENU_B_X1
#define MENU_BUTTON2_T MENU_B_Y0

#define MENU_BUTTON3_L MENU_B_X2
#define MENU_BUTTON3_T MENU_B_Y0

#define MENU_BUTTON4_L MENU_B_X0
#define MENU_BUTTON4_T MENU_B_Y1

#define MENU_BUTTON5_L MENU_B_X1
#define MENU_BUTTON5_T MENU_B_Y1

#define MENU_BUTTON6_L MENU_B_X2
#define MENU_BUTTON6_T MENU_B_Y1

#define MENU_BUTTON7_L MENU_B_X0
#define MENU_BUTTON7_T MENU_B_Y2

#define MENU_BUTTON8_L MENU_B_X1
#define MENU_BUTTON8_T MENU_B_Y2

#define MENU_BUTTON9_L MENU_B_X2
#define MENU_BUTTON9_T MENU_B_Y2

#define MENU_BUTTON_W_H 240 //W=H

/*----omat ohjelmat etc */
#define MENU_B_SMALL_X0  20
#define MENU_B_SMALL_X1 280
#define MENU_B_SMALL_X2 540

#define MENU_B_SMALL_Y0  90
#define MENU_B_SMALL_Y1 272
#define MENU_B_SMALL_Y2 452
#define MENU_B_SMALL_Y3 632
#define MENU_B_SMALL_Y4 812

#define MENU_BUTTONSMALL1_L MENU_B_SMALL_X0
#define MENU_BUTTONSMALL1_T MENU_B_SMALL_Y0

#define MENU_BUTTONSMALL2_L MENU_B_SMALL_X1
#define MENU_BUTTONSMALL2_T MENU_B_SMALL_Y0

#define MENU_BUTTONSMALL3_L MENU_B_SMALL_X2
#define MENU_BUTTONSMALL3_T MENU_B_SMALL_Y0

#define MENU_BUTTONSMALL4_L MENU_B_SMALL_X0
#define MENU_BUTTONSMALL4_T MENU_B_SMALL_Y1

#define MENU_BUTTONSMALL5_L MENU_B_SMALL_X1
#define MENU_BUTTONSMALL5_T MENU_B_SMALL_Y1

#define MENU_BUTTONSMALL6_L MENU_B_SMALL_X2
#define MENU_BUTTONSMALL6_T MENU_B_SMALL_Y1

#define MENU_BUTTONSMALL7_L MENU_B_SMALL_X0
#define MENU_BUTTONSMALL7_T MENU_B_SMALL_Y2

#define MENU_BUTTONSMALL8_L MENU_B_SMALL_X1
#define MENU_BUTTONSMALL8_T MENU_B_SMALL_Y2

#define MENU_BUTTONSMALL9_L MENU_B_SMALL_X2
#define MENU_BUTTONSMALL9_T MENU_B_SMALL_Y2

#define MENU_BUTTONSMALL10_L MENU_B_SMALL_X0
#define MENU_BUTTONSMALL10_T MENU_B_SMALL_Y3

#define MENU_BUTTONSMALL11_L MENU_B_SMALL_X1
#define MENU_BUTTONSMALL11_T MENU_B_SMALL_Y3

#define MENU_BUTTONSMALL12_L MENU_B_SMALL_X2
#define MENU_BUTTONSMALL12_T MENU_B_SMALL_Y3

#define MENU_BUTTONSMALL13_L MENU_B_SMALL_X0
#define MENU_BUTTONSMALL13_T MENU_B_SMALL_Y4

#define MENU_BUTTONSMALL14_L MENU_B_SMALL_X1
#define MENU_BUTTONSMALL14_T MENU_B_SMALL_Y4

#define MENU_BUTTONSMALL15_L MENU_B_SMALL_X2
#define MENU_BUTTONSMALL15_T MENU_B_SMALL_Y4

#define MENU_BUTTONSMALL_W 240
#define MENU_BUTTONSMALL_H 160


extern void load_all_images(void);
extern void delete_all_images(void);

#include "image.h"

enum e_images
{
   IMAGE_DIETA_MX500,
   IMAGE_DIETA_LOGO,
   IMAGE_MENU_BUTTON_TAUSTA,
   IMAGE_MENU_BUTTON_POHJASSA_TAUSTA,
   IMAGE_MENU_BUTTON_SMALL_TAUSTA,
   IMAGE_MENU_BUTTON_SMALL_POHJASSA_TAUSTA,

   IMAGE_KYPSENNYS_111px,
   IMAGE_JAAHDYTYS_111px,
   IMAGE_SUOSIKIT_111px,
   IMAGE_PUHDISTUS_111px,
   IMAGE_OHJELMAT_111px,
   IMAGE_Ekstrat_111px,
   IMAGE_OMAT_OHJELMAT_111px,
   IMAGE_AUTOCOOK_111px,

   IMAGE_KYPS_JA_JAAH_HARMAA,
   IMAGE_KYPS_JA_JAAH_HARMAA_VASEN_POHJASSA,
   IMAGE_KYPS_JA_JAAH_HARMAA_OIKEA_POHJASSA,
   IMAGE_KYPS_JA_JAAH_HARMAA_TAYSIN_POHJASSA,

   IMAGE_KYPS_JA_JAAH_PUNAINEN,
   IMAGE_KYPS_JA_JAAH_SININEN,

   IMAGE_VIHREA_LYHYT,
   IMAGE_VIHREA_LYHYT_POHJASSA,
   IMAGE_VIHREA_PITKA,
   IMAGE_VIHREA_PITKA_POHJASSA,
   IMAGE_PUNAINEN_PITKA,
   IMAGE_PUNAINEN_PITKA_POHJASSA,
   IMAGE_ASETUKSET_YLAPAINIKE_HARMAA,
   IMAGE_ASETUKSET_YLAPAINIKE_HARMAA_POHJASSA,
   IMAGE_ASETUKSET_YLAPAINIKE_VALKOINEN,
   IMAGE_ASETUKSET_YLAPAINIKE_VALKOINEN_POHJASSA,

   IMAGE_HARMAA,
   IMAGE_HARMAA_POHJASSA,
   IMAGE_VALKOINEN_VIHREAT_REUNAT,
   IMAGE_VALKOINEN_VIHREAT_REUNAT_POHJASSA,
   IMAGE_PUNAINEN,

   IMAGE_PIENI_NUMERO_POHJA,
   IMAGE_PIENI_NUMERO_POHJA_POHJASSA,
   IMAGE_PIENI_BACKSPACE,
   IMAGE_PIENI_BACKSPACE_POHJASSA,
   IMAGE_PIENI_OK_1,

   IMAGE_NUMERO_POHJA,
   IMAGE_NUMERO_POHJA_POHJASSA,
   IMAGE_BACKSPACE,
   IMAGE_BACKSPACE_POHJASSA,
   IMAGE_OK_1,

   IMAGE_KIRJAIN_POHJA,
   IMAGE_KIRJAIN_POHJA_POHJASSA,
   IMAGE_KIRJAIN_BACKSPACE,
   IMAGE_KIRJAIN_BACKSPACE_POHJASSA,
   IMAGE_KIRJAIN_SPACE,
   IMAGE_KIRJAIN_SPACE_POHJASSA,
   IMAGE_KIRJAIN_OK,
   IMAGE_MUSTA_RETURN_32px,
   IMAGE_NUOLI_ALAS_32px,

   IMAGE_ALAVALIKKO_POHJA,
   IMAGE_ALAVALIKKO_POHJA_PAINETTU,
   IMAGE_ALAVALIKKO_TOIMINTO1,
   IMAGE_ALAVALIKKO_TOIMINTO2,
   IMAGE_ALAVALIKKO_TOIMINTO3,

   IMAGE_MUSTA_LIEKKI_58px,
   IMAGE_VALKOINEN_AJASTUS_58px,
   IMAGE_VALKOINEN_SEKOITUS_58px,
   IMAGE_SININEN_HANA_58px,
   IMAGE_VALKOINEN_PYRAMIDI_58px,
   IMAGE_VALKOINEN_PYRAMIDI_NURIN_58px,
   IMAGE_PLAY_58px,
   IMAGE_PAUSE_58px,
   IMAGE_MUSTA_AJASTUS_58px, //Nämä seuraavat mustat + mustaliekki_58 on ohj.vaiheen teossa käytössä, mutta onko oikeat vai pitäskö olla 45px?
   IMAGE_MUSTA_PISARA_58px,
   IMAGE_MUSTA_SEKOITUS_58px,

   IMAGE_PUNAINEN_LIEKKI_76px,
   IMAGE_SININEN_JAAHDYTYS_76px,
   IMAGE_VALKOINEN_JAAHDYTYS_76px, //Jäähd. sininen+valkoinen pidettävä peräkkäin
   IMAGE_VALKOINEN_AJASTUS_76px,
   IMAGE_VALKOINEN_SEKOITUS_76px,
   IMAGE_SININEN_HANA_76px,
   IMAGE_VALKOINEN_PYRAMIDI_76px,
   IMAGE_VALKOINEN_RETURN_76px,
   IMAGE_MUISTIINPANOT_B_76px,

   IMAGE_TEMP_VALINTA_LISATOIMINTO,
   IMAGE_TEMP_VALINTA_LISATOIMINTO_POHJASSA,
   IMAGE_TEMP_VALINTA_LISATOIMINTO_VALITTU,
   IMAGE_TEMP_VALINTA_LISATOIMINTO_VALITTU_POHJASSA,

   IMAGE_RUOKA_LAMPO_IKONI_B_45px, //Näitten lämpötila-ikonien Järjestys säilytettävä (Black, sitten White)
   IMAGE_RUOKA_LAMPO_IKONI_W_45px, //Ruoan lämpötila ikoni White, Järjestys säilytettävä
   IMAGE_VAIPPA_LAMPO_IKONI_B_45px,
   IMAGE_VAIPPA_LAMPO_IKONI_W_45px, //VAipan lämpötila ikoni White
   IMAGE_DELTA_LAMPO_IKONI_B_45px,
   IMAGE_DELTA_LAMPO_IKONI_W_45px,
   IMAGE_SENSOR_LAMPO_IKONI_B_45px,
   IMAGE_SENSOR_LAMPO_IKONI_W_45px,

   IMAGE_SEKOITUSTAPA_VAALEA_BTN,
   IMAGE_SEKOITUSTAPA_VAALEA_POHJASSA_BTN,
   IMAGE_SEKOITUSTAPA_VAALEA_VALITTU_BTN,

   IMAGE_SEKOITUSTAPA_KUVA_YHTEEN_SUUNTAAN,
   IMAGE_SEKOITUSTAPA_KUVA_KAHTEEN_SUUNTAAN,
   IMAGE_SEKOITUSTAPA_KUVA_KAHTEEN_SUUNTAAN_HIDAS,
   IMAGE_SEKOITUSTAPA_KUVA_KAHTEEN_SUUNTAAN_NOPEA,

   IMAGE_YLAPALKKI_KUVAT_TOIMINTO1,
   IMAGE_YLAPALKKI_KUVAT_TOIMINTO2,
   IMAGE_YLAPALKKI_KUVAT_TOIMINTO3,
   IMAGE_YLAPALKKI_KUVAT_TOIMINTO4,
   IMAGE_YLAPALKKI_KUVAT_TOIMINTO5,
   IMAGE_YLAPALKKI_KUVAT_TOIMINTO6,

   IMAGE_LIPPU_FIN,
   IMAGE_LIPPU_ENG,
   IMAGE_LIPPU_SWE,

   IMAGE_RESEPTIN_MUOKKAUS_PAINIKE,
   IMAGE_RESEPTIN_MUOKKAUS_PAINIKE_POHJASSA,

   IMAGE_SIVUPALKKI_FULL_BASE,
   IMAGE_SIVUPALKKI_COMB_FS,
   IMAGE_SIVUPALKKI_FOUR_SQ,

   IMAGE_SIVUPALKKI_ICON_COOK,
   IMAGE_SIVUPALKKI_ICON_CHILL,
   IMAGE_SIVUPALKKI_ICON_AIKA,
   IMAGE_SIVUPALKKI_ICON_VESI,
   IMAGE_SIVUPALKKI_ICON_SEK,
   IMAGE_SIVUPALKKI_ICON_LAPPU,

   NUM_LOADED_IMAGES
};
extern Image * image_ptrs[NUM_LOADED_IMAGES];

extern void render_text(char * str, int x, int y, SDL_Color *color_p, TTF_Font *font_p, int utf8=0);
extern void render_text_center(char * str, int x, int y, SDL_Color *color_p, TTF_Font *font_p, int utf8=0);

#endif
