#ifndef TEKSTIT_H
#define TEKSTIT_H

#define TXT_GROUP_YLEIS 1
#define TXT_GROUP_SEKOITUSTAPA 2
#define TXT_GROUP_RUOKA_VALMIS 3
#define TXT_GROUP_KANSIO_NIMET 4

extern const char * yleis_tekstit[];

enum yleis_tekstit_enum {
   YLEIS_TXT_ALOITA,
   YLEIS_TXT_LOPETA,
   YLEIS_TXT_VALMIS,
   YLEIS_TXT_KYPSENNYS,
   YLEIS_TXT_JAAHDYTYS,
   YLEIS_TXT_SUOSIKIT,
   YLEIS_TXT_PESU,
   YLEIS_TXT_OHJELMAT,
   YLEIS_TXT_LISATOIMINNOT,
   YLEIS_TXT_YLLAPITO,
   YLEIS_TXT_OMAT_OHJELMAT,
   YLEIS_TXT_AUTOCOOK,
   YLEIS_TXT_HACCP,
   YLEIS_TXT_JATKA_PALAA,
   YLEIS_TXT_TALLENNA,
   YLEIS_TXT_HALUATKO_LOPETTAA_OHJELMAN,
   YLEIS_TXT_HALUATKO_SAMMUTTAA_LAITTEEN,
   YLEIS_TXT_TAKAISIN,
   YLEIS_TXT_UUSI_OHJELMA,
   YLEIS_TXT_OK,
   YLEIS_TXT_KAYTTAJAPROFIILI,
   YLEIS_TXT_SALASANA,
   YLEIS_TXT_PERUSKAYTTAJA,
   YLEIS_TXT_SUPERKAYTTAJA,
   YLEIS_TXT_HUOLTOKAYTTAJA,
   YLEIS_TXT_LISAA_UUSI_KANSIO,
   YLEIS_TXT_SIJAINTI,
   YLEIS_TXT_VALITSE_SIJAINTI,
   YLEIS_TXT_OHJELMAN_NIMI,
   YLEIS_TXT_TYOKALU,
   YLEIS_TXT_RESEPTIN_KUVAUS,
   YLEIS_TXT_ARVIOITU_VALMISTUMIS_AIKA,
   YLEIS_TXT_KOKONAISMAARA,
   YLEIS_TXT_VALMISTUSERAN_KOKO,
   YLEIS_TXT_TUOTANTOMAARA_KG,
   YLEIS_TXT_KEITTOERAN_NMO,
   YLEIS_TXT_UUSI_VAIHE,
   YLEIS_TXT_KAYTETTY_ENITEN,
   YLEIS_TXT_KAYTETTY_VIIMEKSI,
   YLEIS_TXT_AAKKOSJARJESTYS,
   YLEIS_TXT_VAIHETTA,
   YLEIS_TXT_OHJELMA_VERSIO_LOYTYI,
   YLEIS_TXT_NYKYINEN_VERSIO_ON_JO_UUSIN,
   YLEIS_TXT_PAIVITYS_TEHTY_UUDELLEENKAYNNISTA,
   NUM_YLEIS_TEKSTIT
};

extern const char * sekoitustapa_tekstit[];

enum sekoitustapa_tekstit_enum {
   SEKOITUSTAPA_TXT_KAHTEEN_SUUNTAAN_HIDAS,
   SEKOITUSTAPA_TXT_YHTEEN_SUUNTAAN,
   SEKOITUSTAPA_TXT_KAHTEEN_SUUNTAAN,
   SEKOITUSTAPA_TXT_YHTEEN_SUUNTAAN_TAUKO,
   SEKOITUSTAPA_TXT_KAHTEEN_SUUNTAAN_NOPEA,
   SEKOITUSTAPA_TXT_YHTEEN_SUUNTAAN_PITKA_TAUKO,
   SEKOITUSTAPA_TXT_KAHTEEN_SUUNTAAN_TAUKO,
   SEKOITUSTAPA_TXT_OMA_SEKOITUSTAPA,
   SEKOITUSTAPA_TXT_SEKOITUSTAPA_JA_NOPEUS,
   NUM_SEKOITUSTAPA_TEKSTIT
};

extern const char * tyokalut_tekstit[];

enum tyokalut_tekstit_enum {
   TYOKALUT_TXT_YLEISTYOKALU,
   TYOKALUT_TXT_VISPAUSRITILA_JA_POHJAKAAVIN,
   TYOKALUT_TXT_MASSAKOUKKU_JA_POHJAKAAVIN,
   TYOKALUT_TXT_MASSAKOUKKU,
   NUM_TYOKALUT_TEKSTIT
};

extern const char * ruoka_valmis_tekstit[];

enum ruoka_valmis_tekstit_enum {
   RUOKA_VALMIS_TXT_RUOKA_ON_VALMIS,
   RUOKA_VALMIS_TXT_RESEPTI,
   RUOKA_VALMIS_TXT_ERANUMERO,
   RUOKA_VALMIS_TXT_RESEPTIN_SAANTO,
   RUOKA_VALMIS_TXT_SAANTO,
   RUOKA_VALMIS_TXT_PAINO,
   RUOKA_VALMIS_TXT_OHJELMAN_KOKONAISAIKA,
   RUOKA_VALMIS_TXT_KOKONAISAIKA,
   RUOKA_VALMIS_TXT_JAAHDYTYSAIKA,
   RUOKA_VALMIS_TXT_KOKONAISVESIMAARA,
   RUOKA_VALMIS_TXT_ENERGIAN_KULUTUS,
   NUM_RUOKA_VALMIS_TEKSTIT
};

extern const char * kansio_nimet_tekstit[];

enum kansio_nimet_enum {
   KANSIO_NIMET_TXT_KEITOT,
   KANSIO_NIMET_TXT_LAMPIMAT_KASTIKKEET,
   KANSIO_NIMET_TXT_KYLMAT_KASTIKKEET,
   KANSIO_NIMET_TXT_PUUROT,
   KANSIO_NIMET_TXT_RIISI,
   KANSIO_NIMET_TXT_PASTA,
   KANSIO_NIMET_TXT_PATARUOAT,
   KANSIO_NIMET_TXT_PERUNA,
   KANSIO_NIMET_TXT_JALKIRUOAT,
   KANSIO_NIMET_TXT_VANUKKAAT,
   KANSIO_NIMET_TXT_SEOKSET,
   KANSIO_NIMET_TXT_PESUOHJELMAT,
   NUM_KANSIO_NIMET_TEKSTIT
};

extern const char * error_tekstit[];

enum error_tekstit_enum {
   ERROR_IDX_CAN_COMM_ERROR,
   ERROR_IDX_RUOKA_ANTURI_KATKOS_ERROR,
   ERROR_IDX_VAIPPA_ANTURI_KATKOS_ERROR,
   ERROR_IDX_RUOKA_ANTURI_OIKOSULKU_ERROR,
   ERROR_IDX_VAIPPA_ANTURI_OIKOSULKU_ERROR,
   ERROR_IDX_VESIMITTARI_ERROR,
   ERROR_IDX_HATASEIS_PAINETTU,
   ERROR_IDX_KONTAKTORI_VIKA,
   ERROR_IDX_PAINEKYTKIN_LAUENNUT,
   ERROR_IDX_VAST_YLIKUUM_SUOJA_LAUENNUT,
   NUM_ERROR_INDEX
};

extern int errors_paalla[NUM_ERROR_INDEX]; //errors_paalla ja error_tekstit vastaavat toisiaan

#endif